PACKAGE_NAME="asus-ec-fan"
PACKAGE_VERSION="0.1.0"
BUILT_MODULE_NAME[0]="asus_ec_fan"
BUILT_MODULE_LOCATION[0]="kernel"
DEST_MODULE_LOCATION[0]="/updates/dkms"
AUTOINSTALL="yes"
MAKE[0]="make -C kernel KDIR=/lib/modules/${kernelver}/build"
CLEAN="make -C kernel KDIR=/lib/modules/${kernelver}/build clean"
